newslist/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('', include('newslistapp.urls', namespace='newslistapp')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('users/', include('django.contrib.auth.urls')),
]

newslistapp/urls.py
from django.urls import path, include
from . import views
from .views.views import mypage, StockNews, delete_stock
from .views.index import index

app_name='newslistapp'
urlpatterns = [
    path('', index, name='index'),
    path('mypage/', mypage, name='mypage'),
    path('stock/', StockNews.as_view(), name='stock'),
    path('delete_stock/<int:pk>/', delete_stock, name='delete_stock'),
]

users/urls.py
from django.urls import path
from . import views
from .views import signup

app_name = 'users'
urlpatterns = [
    path('signup/', signup, name='signup'),
]

templates/base.html
<!doctype html>
{% load static %}
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'stylesheet.css' %}">

    <link rel="icon" type="image/png" href="{% static 'favicon.ico' %}">

    <!-- load jQuery -->
    <script src="{% static 'jquery-3.5.1.min.js' %}"></script>

    {% block customcss %}
    {% endblock customcss %}
    
    <title>ScrapeNews</title>
  </head>
  <body>
    
    <!-- ヘッダー -->
    <nav class="navbar navbar-dark bg-dark sticky-top p-0">
      <div class="container py-1">
        <a class="navbar-brand" href="{% url 'newslistapp:index' %}">
          <img src="{% static 'logo.png' %}" width="160px" height="32px" class="d-inline-block align-top img-fluid" alt="ScrapeNews">
        </a>
        <ul class='navbar-nav list-group-horizontal ml-auto pr-3'>
          {% if user.is_authenticated %}
              <li class='nav-time'>
                  <span class='navbar-text'>{{ user }} - </span>
              </li>
              <li class='nav-item'>
                  <a href='{% url "logout" %}' class='logout nav-link'>Logout</a>
              </li>
          {% else %}
              <a href='{% url "login" %}' class='login nav-link'>Login</a>
          {% endif %}
        </ul>
        {% if user.is_authenticated %}
          <a href="{% url 'newslistapp:mypage' %}"><button class="btn btn-outline-info my-sm-0" type="submit">MyPage</button></a>
        {% else %}
          <a href="{% url 'users:signup' %}"><button class="btn btn-outline-info my-sm-0" type="submit">Signup</button></a>
          {% endif %}
        </div>
        <div class="container-fluid justify-content-center bg-info" id="s_alert">
          <div id="resultPOST" class="text-light"></div>
        </div>
      </nav>
      
      <!-- メイン -->
      <div class="bg-light">
        <div class="container">

        {% block content %}
          
        {% endblock content %}
        
      </div>
      
          <div class="text-center py-3 bg-secondary">
            <a class="" href="{% url 'newslistapp:index' %}">
              <img src="{% static 'logo.png' %}" width="160px" height="32px" class="d-inline-block align-top img-fluid" alt="ScrapeNews">
            </a>
            <div class="text-light" style="font-size:3px;">
              Logo created by 
              <a href="https://www.designevo.com/logo-maker/" title="Free Online Logo Maker" class="text-light" style="font-size:3px;">
                DesignEvo logo maker
              </a>
              <br>
              <br>
              © Naoki Nishimura
            </div>
          </div>
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <!-- <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script> -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}

<h3 class='border-bottom border-gray pt-5 pb-2'>ニュース一覧</h3>

<ul class="list-unstyled">
  {% for target, icon, title, date, url in news_list %}
    {% if forloop.counter0|divisibleby:"2" %}
      <li class="media border-bottom border-gray pt-3 pb-1 px-1">
    {% else %}
      <li class="media border-bottom border-gray pt-3 pb-1 px-1 bg-white">
    {% endif %}
    {% if icon == 'm' %}
      <div style='width: 60px;'>
        <i class="fas fa-chart-bar p-2 h2 rounded text-secondary fa-border  marketing"></i>
      </div>
    {% elif icon == 'n' %}
    <div style='width: 60px;'>
      <i class="far fa-newspaper p-2 h2 rounded text-secondary fa-border news"></i>
    </div>
    {% elif icon == 'p' %}
    <div style='width: 60px;'>
      <i class="fas fa-laptop-code p-2 h2 rounded text-secondary fa-border programing"></i>
    </div style='width: 60px;'>
    {% elif icon == 'i' %}
    <div>
      <i class="fas fa-chalkboard-teacher p-2 h2 rounded text-secondary fa-border improvement"></i>
    </div>
    {% endif %}
    <div class="media-body pl-3">
      <a href="{{ url }}" class="">
        <h6 class="mt-0 mb-0 text-body">{{ title|truncatewords_html:10 }}</h5>
          <span class="mb-0 small text-secondary">{{ target }}</span>
          <span class="mb-0 small text-secondary pl-2 pr-2">{{ date }}</span>
        <span class="mb-0 small text-secondary">{{ url|truncatechars_html:50 }}</span>
      </a>

      {% if user.is_authenticated %}
        <form action="{% url 'newslistapp:stock' %}" method="post">{% csrf_token %}
          <input type="hidden" name="user" value="{{ user.id }}">
          <input type="hidden" id="title" name="title" value="{{ title }}">
          <input type="hidden" name="name" value="{{ target }}">
          <input type="hidden" name="url" value="{{ url }}">
          <input type="hidden" name="icon" value="{{ icon }}">
          {% if title in title_list %}
            <input type="submit" value="&#xf02e; stock" class="float-right btn btn-secondary btn-sm fas" role="button" style='cursor: default;' disabled>
          {% else %}
            <input type="submit" id="button{{ forloop.counter }}" value="&#xf02e; stock" class="float-right btn btn-secondary btn-sm fas" role="button">
          {% endif %}
        </form>
        
        <script>
          $("form").submit( function(event) {
            event.preventDefault();
            let form = $(this);
            $('#resultPOST').text('通信中...');
            // Ajax通信を開始
            $.ajax({
              url: form.prop("action"),
              method: form.prop("method"),
              data: form.serialize(),
              timeout: 5000,
              dataType: "text",
            })
            .done( function(data) {
              // 通信成功時の処理を記述
              let element = document.getElementById("s_alert");
              element.classList.replace('bg-danger', 'bg-info');
              $('#resultPOST').text('記事を保存しました');
            })
            .fail(function() {
              // 通信失敗時の処理を記述
              let element = $("s_alert");
              element.classList.replace('bg-info', 'bg-danger');
              $('#resultPOST').text('記事の保存に失敗しました');
            });
          });
        </script>
      {% endif %}
    </div>
  </li>
  {% endfor %}
        
</ul>

        <script>
          $("form").submit( function(event) {
            event.preventDefault();
            let form = $(this);
            $('#resultPOST').text('通信中...');
            // Ajax通信を開始
            $.ajax({
              url: form.prop("action"),
              method: form.prop("method"),
              data: form.serialize(),
              timeout: 5000,
              dataType: "text",
                  })
            .done( function(data) {
              // 通信成功時の処理を記述
              $('#resultPOST').text('記事を保存しました');
            })
            .fail(function() {
              // 通信失敗時の処理を記述
              $('#resultPOST').text('記事の保存に失敗しました');
            });
          });
        </script>

{% endblock content %}

templates/mypage.html
{% extends 'base.html' %}

{% block content %}

<h3 class='border-bottom border-gray pt-5 pb-2'>保存したニュース一覧</h3>

<ul class="list-unstyled">
  {% for article in articles %}
    {% if forloop.counter0|divisibleby:"2" %}
      <li class="media border-bottom border-gray pt-3 pb-1 px-1">
    {% else %}
      <li class="media border-bottom border-gray pt-3 pb-1 px-1 bg-white">
    {% endif %}
    {% if article.icon == 'm' %}
    <div style='width: 60px;'>
      <i class="fas fa-chart-bar p-2 h2 rounded text-secondary fa-border marketing"></i>
    </div>
    {% elif article.icon == 'n' %}
    <div style='width: 60px;'>
      <i class="far fa-newspaper p-2 h2 rounded text-secondary fa-border news"></i>
    </div>
    {% elif article.icon == 'p' %}
    <div style='width: 60px;'>
      <i class="fas fa-laptop-code p-2 h2 rounded text-secondary fa-border programing"></i>
    </div>
    {% elif article.icon == 'i' %}
    <div style='width: 60px;'>
      <i class="fas fa-chalkboard-teacher p-2 h2 rounded text-secondary fa-border improvement"></i>
    </div>
  {% endif %}
    <div class="media-body pl-3">
      <a href="{{ article.url }}" class="">
        <h6 class="mt-0 mb-0 text-body">{{ article.title|truncatewords_html:10 }}</h5>
          <span class="mb-0 small text-secondary">{{ article.name }}</span>
          <span class="mb-0 small text-secondary pl-2 pr-2">{{ article.created_at }}</span>
        <span class="mb-0 small text-secondary">{{ article.url }}</span>
      </a>
      <!-- <div class="btn-group-toggle float-right" data-toggle="buttons">
        <label class="btn btn-secondary btn-sm">
          <input type="checkbox" checked autocomplete="off">STOCK
        </label>
      </div>
      -->
      <form action="{% url 'newslistapp:delete_stock' pk=article.pk %}" method="post">{% csrf_token %}
        <button type="submit" class="float-right btn btn-secondary btn-sm fas fa-trash-alt" onclick='return confirm("本当に削除しますか？");'> delete</button>
      </form>
    </div>
  </li>
  {% endfor %}
</ul>

</div>
{% endblock content %}

templates/signup.html
{% extends 'base.html' %}

{% block content %}
  <div class='vh-100'>
    <h1>Sign up</h1>
    <!-- <form action="{% url 'users:signup' %}"method='post'>{% csrf_token %}
      <div class="form-group">
        <label for="exampleInputEmail1">ユーザー名：</label><br>
        {{ signup_form.username }}
        <small id="emailHelp" class="form-text text-muted"></small>
      </div>
      <div class="form-group">
        <label for="exampleInputPassword1">Password：</label><br>
        {{ signup_form.password }}
      </div>
      <div class="form-group">
        <label for="exampleInputPassword1">Password：</label><br>
        {{ signup_form.password1 }}
      </div>
      <div class="form-group">
        <label for="exampleInputPassword1">Password(確認用)：</label><br>
        {{ signup_form.password2 }}
      </div>
      <button type="submit" class="btn btn-primary">Sign up</button>
    </form>
     -->


    <section class='common-form'>
      <form action="{% url 'users:signup' %}"method='post'>{% csrf_token %}
        {{ signup_form.as_p }}
          {% for error in signup_form.username.errors %}
            <span class="text-warning">{{ error }}</span>
          {% endfor %}
        <button type='submit'>Sign up</button>
      </form>
    </section>
  </div>
{% endblock %}